<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAbUsjrC\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAbUsjrC/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerAbUsjrC.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerAbUsjrC\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerAbUsjrC\appAppKernelProdContainer([
    'container.build_hash' => 'AbUsjrC',
    'container.build_id' => '2b1dcae1',
    'container.build_time' => 1698315255,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAbUsjrC');
